### ISSUE TITLE
Improve password storage

### ISSUE THREAD

**Issue by jacob-grahn** [jacob-grahn/platform-racing-2-server#1]
Passwords are currently hashed with sha1, and all passwords share the same salt. Neither of these things are good!

**Comment by bls1999** [comment]
Indeed, those things are not good at all.

I can script something later that uses the password_hash() and password_verify() functions.  In the meantime, let me know if:
1) you intend to convert all accounts to this method of encryption.
2) this is a kind of encryption in which you'd be comfortable having PR2 passwords.

**Comment by jacob-grahn** [comment]
I think the first step would be to convert passwords as people log in. 

- get user and pass
- hash pass with old method and new method
- check both hashes against the stored hash
- if the old hash matches, update db record to the new hash

This won’t help old abandoned accounts, but it will at least be better for current users.

Updating the old hashes on abandoned accounts may involve generating a rainbow table with the salt, that’s the only solution I can come up with!

**Comment by bls1999** [comment]
I'll see what I can do!

**Comment by bls1999** [comment]
@jacob-grahn what if there were two columns in the database, one for the old hash and one for the new one? Then, on login, the process would be:
 - Check both the old and new hash columns
 - If the old is not null and the sha1 hash matches, rehash the password on login using password_hash(), erase the old sha1 hash, and mark the new one in the new column.
 - If the new is not null, check the password using password_verify() and continue with the login process as normal.

In this way, it would be easy to avoid using rainbow tables; Although, since I'm not particularly acquainted with the different kinds of newfangled attacks these days, I have no idea if this would be secure or not.

Also, in looking through your code, I noticed that you're using addslashes() instead of mysqli_real_escape_string().  Would that be easy to update for the new passwords as well?

**Comment by jacob-grahn** [comment]
Yeah, we can probably do a mysqli_real_escape_string switcheroo throughout the whole code base all at once. 

Here's a thought! We can't just generate a new hash for old accounts because we don't know what their password is. But what if we treat the old hash as the password for the new hash? Then we could update all of the hashes for every account at the same time. Then the login check would go like this:

- $password = sha1($real_password . $salt)
- password_verify($password, $hash_in_db)

**Comment by bls1999** [comment]
That's a pretty good way to go about it!  Then there's double the encryption, we avoid rainbow tables, the database structure stays the same (I think?), and all the accounts get secured.  Score!

So what would need to happen in order to make that work?

**Comment by aaaaaa123456789** [comment]
Do keep in mind that `password_hash()` and `password_verify()` have the little issue of truncating passwords. (To 72 characters, but truncating passwords is always an issue.) This is because they use Blowfish, for which output size grows linearly with input size — in order to generate a limited size output, its only recourse is to limit the size of the input.

A much better alternative is to use the `crypt()` function with a properly generated salt value and a strong hashing algorithm, like SHA-512. Generation of the salt is a bit of a sensitive issue, but there are plenty of good ways to do it, including simply reading a few bytes from the `/dev/random` file, seeding the random generator through `mt_srand()` and using `mt_rand()` to generate the salt characters. (Do make sure to read the documentation for all these functions in order to know which ranges of characters are valid.)

**Comment by bls1999** [comment]
@aaaaaa123456789 to give credit where credit is due, you definitely have more experience in this field than I do.  Could you write it?

**Comment by aaaaaa123456789** [comment]
Please note that the following code is untested. Tell me if there are bugs you cannot fix.

```php
function generate_random_salt () {
  $file = fopen('/dev/random', 'rb');
  if ($file === false) throw new Exception('could not open /dev/random');
  $data = fread($file, 4);
  fclose($file);
  $salts = array();
  for ($p = 0; $p < 4; $p ++) {
    for ($skip = ord($data[$p]); $skip; $skip --) mt_rand();
    $salts[$p] = mt_rand() | (($ord & 1) ? 0x80000000 : 0);
  }
  return strtr(base64_encode(pack('l*', $salts[0], $salts[1], $salts[2], $salts[3])), '+', '.');
}

function hash_pw ($password) {
  $salt = generate_random_salt();
  return crypt($password, '$6$rounds=5000$' . $salt);
}

function check_pw ($password, $check) {
  if ((strlen($check) == 40) && ($check[0] != '$')) return $check == sha1($password); // back compat
  return crypt($password, $check) == $check;
}```

**Comment by jacob-grahn** [comment]
Thanks @aaaaaa123456789, I'll get this implemented and tested over the course of the next few days.

### Todo
- [ ] create a new hash column in the db
- [ ] check for new hash or legacy hash during login
- [ ] generate a new hash during account creation
- [ ] generate a new hash during a password update
- [ ] create a new hash for everyone in the db
- [ ] remove legacy hash check during login
- [ ] remove legacy hash column from db

**Comment by isokissa3** [comment]
@aaaaaa123456789 Version is not safe against timing attacks, hash_equals should be used instead of == when comparing strings

Another option is to pre hash the password and return it as raw bytes, base64 encode the raw bytes and pass it to password_hash

**Comment by aaaaaa123456789** [comment]
Timing attacks are very irrelevant when the password input is through the
internet (where the variations in latency are at least four orders of
magnitude than the time it takes to compare strings) and the passwords are
entered unhashed anyway.
The impact of this putative vulnerability is zero, and it adds complexity
for no reason. Don't worry about it.

**Comment by jacob-grahn** [comment]
I'm generating new hashes for everyone in the db now. It takes a while to generate millions of bcrypt hashes though. That's kind of the point, but yeah.

**Comment by jacob-grahn** [comment]
This is all done now. Most of the changed code is on pr2hub.com, which is not (yet) a part of this repo. If there are any new problems with passwords as a result of my changing things around, let's open up a new issue for it.
